config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :events do
    member do
      post 'toggle_attendance'
    end
  end
  resources :users, only: [:show]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :attendee, class_name: 'User', foreign_key: 'attendee_id'
    belongs_to :attended_event, class_name: 'Event', foreign_key: 'attended_event_id'
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
    has_many :attendances, foreign_key: 'attended_event_id', dependent: :destroy
    has_many :attendees, through: :attendances, source: :attendee

    validates :title, presence: true
    validates :description, presence: true
    validates :event_date, presence: true

    scope :past_events, -> {where('event_date < ?', Date.current)}

    scope :upcoming_events, -> {where('event_date >= ?', Date.current)}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, class_name: 'Event', foreign_key: 'user_id', dependent: :destroy
  has_many :attendances, foreign_key: 'attendee_id', dependent: :destroy
  has_many :attended_events, through: :attendances, source: :attended_event
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    helper_method :attending_event?

    def index
        @past_events = Event.past_events
        @upcoming_events = Event.upcoming_events
    end

    def new
      @event = Event.new
    end

    def create 
        @event = current_user.created_events.build(event_params)
        
        if @event.save
            redirect_to events_path, notice: 'Event was successfully created.'
        else
            render :new,  status: :unprocessable_entity
        end
    end

    def show
        @event = Event.find(params[:id])      
    end

    def edit
        @event = Event.find(params[:id])
    end

    def update
        @event = Event.find(params[:id])

        if @event.update(event_params)
            redirect_to event_path(@event),notice: 'Event was successfully updated.'
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @event = Event.find(params[:id])
        @event.destroy

        redirect_to user_path(current_user), notice: 'Event was successfully destroyed.'      
    end

    def toggle_attendance
        @event = Event.find(params[:id])
        @user = current_user

        attendance = Attendance.find_by(attendee: @user, attended_event: @event)
        
        if attendance
            attendance.destroy
            flash[:notice] = "You have been removed from the event."
        else
            attendance = Attendance.new(attendee: @user, attended_event: @event)
            attendance.save
            flash[:notice] = "You have added to the event."
        end

        redirect_to determine_redirect_path
    end

    private

    def event_params
        params.require(:event).permit(:title, :description, :event_date)      
    end

    def attending_event?(user, event)
        user.attended_events.include?(event)
    end

    def determine_redirect_path
        if request.referer == event_url(@event)
            return event_path(@event)
        elsif request.referer == events_url
            return events_path
        else
            return event_path(@event)
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = current_user
        @created_events = @user.created_events
        @attended_events = @user.attended_events
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :event_date %>
    <%= f.date_field :event_date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= form_with(model: @event, local: true, method: :patch) do |f| %>
    <%= render 'form', f: f %>  
<% end %>

<%= button_to 'Delete Event', @event, 
        method: :delete, 
        data: { confirm: 'Are you sure?' }, 
        class: 'btn btn-danger' %>

app/views/events/index.html.erb
<h2>All Events:</h2>

<div class="upcoming_events">
    <p>Upcoming Events:</p>
    <ul>
        <% @upcoming_events.each do |event| %>
            <li class="event">

                <p class="event_list_body">
                    <%= link_to event.title, event_path(event) %>
                    Created by:
                    <%= event.creator.name%>
                </p>
                <div class="event_list_attend">
                    <% if user_signed_in?%>
                        <%if attending_event?(current_user, event)%>
                            <%= button_to "Unattend", toggle_attendance_event_path(event), method: :post %>
                        <%else%>
                            <%= button_to "Attend", toggle_attendance_event_path(event), method: :post %>
                        <%end%>
                    <%end%>
                </div>
            </li>  
        <% end%>  
    </ul>
</div>

<div class="past_events">
    <p>Past Events:</p>
    <ul>
        <% @past_events.each do |event| %>
            <li class="event">

                <p class="event_list_body">
                    <%= link_to event.title, event_path(event) %>
                    Created by:
                    <%= event.creator.name%>
                </p>
                <div class="event_list_attend">
                    <% if user_signed_in?%>
                        <%if attending_event?(current_user, event)%>
                            <%= button_to "Unattend", toggle_attendance_event_path(event), method: :post %>
                        <%else%>
                            <%= button_to "Attend", toggle_attendance_event_path(event), method: :post %>
                        <%end%>
                    <%end%>
                </div>
            </li>  
        <% end%>  
    </ul>
</div>

app/views/events/new.html.erb
<h1>Create a new Event</h1>

<%= form_with(model: @event, local: true) do |f| %>
   <%= render 'form', f: f %>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.title%></h1>

<% if user_signed_in?%>
    <%if attending_event?(current_user, @event)%>
        <%= button_to "Unattend", toggle_attendance_event_path(@event), method: :post %>
    <%else%>
        <%= button_to "Attend", toggle_attendance_event_path(@event), method: :post %>
    <%end%>
<%end%>

<p class="event-desciption">
    <%= @event.description%>
</p>

<p class="event-creator">
    Created by <%= @event.creator.name%>
</p>

<ul class="attendee_list">
    <% @event.attendees.each do |attendee| %>
        <li class="attendee">
            <%= attendee.name %>
        </li>  
    <% end%> 
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TopPrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'turbo' %>
  </head>

  <body>
    <h1>Create your own Private Event</h1>
    <!-- Navigation bar or other common elements go here -->
    <div class="navbar">
      <ul class="navbar-nav">

        <li class="nav-item right">
          <%= link_to "All events", events_path%>
        </li>

        <% if user_signed_in?%>
          <li class="nav-item right">
            <%= link_to "Create new event", new_event_path%>
          </li>

          <li class="nav-item right">
            <%= link_to "my events", user_path(current_user)%>
          </li>
          
          <li class="nav-item right">
            <%= button_to "User sign out", destroy_user_session_path, 
                method: :delete %>
          </li>

          <li class="nav-item right">
            <%= link_to 'Edit Profile', 
                edit_user_registration_path%>
          </li>
        <% else%>
          <li class="nav-item right">
            <%= link_to "User sign up", new_user_registration_path %>
          </li>
  
          <li class="nav-item right">
            <%= link_to "User sign in", new_user_session_path %>
          </li>

        <%end%>

      </ul>
    </div>

    <!-- Dynamic elements go here -->
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1>Events by <%= @user.name %></h1>

<div class="created_events">
    <div><p><strong>My Created Events</strong></p></div>
    <% if @created_events.any?%>
        <div>
            <ul>
                <% @created_events.each do |event| %>
                    <li class="event-card">
                        <p class="event-title"><strong>
                            <%= link_to event.title, event_path(event) %>
                            </strong></p>
                        <p class="event-description">Description:<%= event.description %></p>
                        <%= link_to "Edit", edit_event_path(event), method: :post %>
                    </li>
                <% end%>
            </ul>
        </div>
    <%else%>
        <p>no events</p>
    <% end%>
</div>

<div class="attended_events">
    <div><p><strong>Events I'm attending</strong></p></div>
    <% if @attended_events.any?%>      
        <div class="past_events">
            <p class="past_events">Past Events:</p>
            <ul>
                <% @user.attended_events.past_events.each do |event| %>
                    <li class="event-card past">
                        <p class="event-title">
                            <strong><%= link_to event.title, event_path(event) %></strong></p>
                        <p class="event-description">Description:<%= event.description %></p>
                    </li>
                <%end%>
            </ul>
        </div>

        <div class="upcoming_events">
            <p class="upcoming_events">Upcoming Events:</p>
            <ul>
                <% @user.attended_events.upcoming_events.each do |event| %>
                    <li class="event-card past">
                        <p class="event-title">
                            <strong><%= link_to event.title, event_path(event) %></strong></p>
                        <p class="event-description">Description:<%= event.description %></p>
                    </li>
                <%end%>
            </ul>
        </div>
    <%else%>
        <p>no events</p>
    <%end%>
</div>